// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: New_gui

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Detecting_Cassette_Spinner = NULL;
lv_obj_t * ui_Detecting_Cassette_ = NULL;
lv_obj_t * ui_Please_Wait = NULL;
lv_obj_t * ui_Spinner1 = NULL;
lv_obj_t * ui_Check_Icon = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    
    /* Set black background */
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Detecting_Cassette_Spinner = lv_spinner_create(ui_Screen2);
    //lv_spinner_set_anim_params(ui_Detecting_Cassette_Spinner, 1000, 90);
    lv_obj_set_width(ui_Detecting_Cassette_Spinner, 80);
    lv_obj_set_height(ui_Detecting_Cassette_Spinner, 80);
    lv_obj_set_x(ui_Detecting_Cassette_Spinner, -232);
    lv_obj_set_y(ui_Detecting_Cassette_Spinner, 48);
    lv_obj_set_align(ui_Detecting_Cassette_Spinner, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Detecting_Cassette_Spinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Detecting_Cassette_Spinner, lv_color_hex(0xF80534), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Detecting_Cassette_Spinner, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Detecting_Cassette_ = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Detecting_Cassette_, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Detecting_Cassette_, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Detecting_Cassette_, 0);
    lv_obj_set_y(ui_Detecting_Cassette_, -85);
    lv_obj_set_align(ui_Detecting_Cassette_, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Detecting_Cassette_, "Detecting Cassette ");
    lv_obj_set_style_text_color(ui_Detecting_Cassette_, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Please_Wait = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Please_Wait, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Please_Wait, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Please_Wait, 0);
    lv_obj_set_y(ui_Please_Wait, 85);
    lv_obj_set_align(ui_Please_Wait, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Please_Wait, "Please Wait");
    lv_obj_set_style_text_color(ui_Please_Wait, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner1 = lv_spinner_create(ui_Screen2);
    //lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 80);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xFF2343), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Check_Icon = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_Check_Icon, &ui_img_check_png);
    lv_obj_set_width(ui_Check_Icon, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Check_Icon, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_Check_Icon, 13);
    lv_obj_set_y(ui_Check_Icon, 10);
    lv_obj_set_align(ui_Check_Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Check_Icon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Check_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_scale(ui_Check_Icon, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    /* Hide checkmark initially */
    lv_obj_add_flag(ui_Check_Icon, LV_OBJ_FLAG_HIDDEN);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Detecting_Cassette_Spinner = NULL;
    ui_Detecting_Cassette_ = NULL;
    ui_Please_Wait = NULL;
    ui_Spinner1 = NULL;
    ui_Check_Icon = NULL;

}
