// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: STM32_GUI_Project

#include "../ui.h"

lv_obj_t * uic_Screen2;
lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Spinner4 = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 1);
    lv_obj_set_y(ui_Label1, -57);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Checking Cassette");

    /* Create simple spinner using arc widget with rotation animation */
    ui_Spinner4 = lv_arc_create(ui_Screen2);
    lv_obj_set_size(ui_Spinner4, 100, 100);
    lv_obj_set_align(ui_Spinner4, LV_ALIGN_CENTER);
    lv_obj_set_y(ui_Spinner4, 50);
    
    /* Set arc angles - show 90 degree arc */
    lv_arc_set_bg_angles(ui_Spinner4, 0, 360);
    lv_arc_set_angles(ui_Spinner4, 0, 90);
    
    /* Style the arc - red indicator */
    lv_obj_set_style_arc_color(ui_Spinner4, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner4, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Spinner4, lv_color_hex(0xF3351E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner4, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    
    /* Simple rotation animation - rotate the whole arc */
    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, ui_Spinner4);
    lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)lv_arc_set_rotation);
    lv_anim_set_values(&a, 0, 360);
    lv_anim_set_time(&a, 2000);  // 2 seconds per rotation
    lv_anim_set_repeat_count(&a, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_path_cb(&a, lv_anim_path_linear);  // Linear path for smooth rotation
    lv_anim_start(&a);

    uic_Screen2 = ui_Screen2;

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    uic_Screen2 = NULL;
    ui_Screen2 = NULL;
    ui_Label1 = NULL;
    ui_Spinner4 = NULL;

}
