// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: STM32_GUI_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Spinner4;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

