// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: STM32_GUI_Project

#ifndef _UI_COMP_SPINNER1_H
#define _UI_COMP_SPINNER1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Spinner1
#define UI_COMP_SPINNER1_SPINNER1 0
#define _UI_COMP_SPINNER1_NUM 1
lv_obj_t * ui_Spinner1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
