// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: STM32_GUI_Project

#include "../ui.h"

// COMPONENT Spinner1

lv_obj_t * ui_Spinner1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Spinner1;
    cui_Spinner1 = lv_spinner_create(comp_parent);
    lv_spinner_set_anim_params(cui_Spinner1, 1000, 90);
    lv_obj_set_width(cui_Spinner1, 80);
    lv_obj_set_height(cui_Spinner1, 80);
    lv_obj_set_align(cui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_SPINNER1_NUM);
    children[UI_COMP_SPINNER1_SPINNER1] = cui_Spinner1;
    lv_obj_add_event_cb(cui_Spinner1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Spinner1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Spinner1_create_hook(cui_Spinner1);
    return cui_Spinner1;
}

